---
apiVersion: v1
kind: Template
metadata:
  name: ingress
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ingress
  spec:
    envName: ${ENV_NAME}
    pods:
    - image: ${IMAGE}:${IMAGE_TAG}
    name: ingress
    livenessProbe:
      failureThreshold: 3
      httpGet:
      path: /api/ingress/v1/version
      port: 8000
      scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      failureThreshold: 3
      httpGet:
      path: /api/ingress/v1/version
      port: 8000
      scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    env:
    - name: INGRESS_STAGEBUCKET
      value: ${INGRESS_STAGEBUCKET}
    - name: INGRESS_VALIDTOPICS
      value: ${INGRESS_VALIDTOPICS} 
    - name: OPENSHIFT_BUILD_COMMIT
      value: somestring
    - name: INGRESS_MINIODEV
      value: "true"
    - name: DEBUG
      value: "true"
    - name: CLOWDER_ENABLED
      value: "true"
    resources:
      limits:
      cpu: 300m
      memory: 8192Mi
      requests:
      cpu: 30m
      memory: 1024Mi
    web: true
    objectStore:
    - ingress-uploads-perma
    kafkaTopics:
    - replicas: 5
      partitions: 5
      topicName: platform.upload.advisor

parameters:
- name: INGRESS_STAGEBUCKET
  value: insights-dev-upload-perm
- name: INGRESS_REJECTBUCKET
  value: insights-dev-upload-rejected
- name: INGRESS_VALIDTOPICS
  value: advisor,advisor-pup,compliance,hccm,qpc,rhv,testareno,tower,leapp-reporting,topological-inventory,buckit,xavier,mkt
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/insights-ingress-go-new
- description: ClowdEnv Name
  name: ENV_NAME
  value: ingress-env

