---
apiVersion: v1
kind: Template
metadata:
  name: ingress
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ingress
  spec:
    envName: ${ENV_NAME}
    pods:
    - name: ingress
      image: ${IMAGE}:${IMAGE_TAG}
      minReplicas: ${REPLICAS}
      livenessProbe:
        failureThreshold: 3
        httpGet:
        path: /
        port: 8080
        scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      readinessProbe:
        failureThreshold: 3
        httpGet:
        path: /
        port: 8080
        scheme: HTTP
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
    env:
    - name: INGRESS_STAGEBUCKET
      value: ${INGRESS_STAGEBUCKET}
    - name: INGRESS_LOG_LEVEL
      value: ${LOG_LEVEL}
    - name: INGRESS_VALIDTOPICS
      value: ${INGRESS_VALIDTOPICS} 
    - name: INGRESS_INVENTORYURL
      value: ${INGRESS_INVENTORYURL} 
    - name: CLOWDER_ENABLED
      value: "true"
    resources:
      limits:
      cpu: ${CPU_LIMIT}
      memory: ${MEMORY_LIMIT} 
      requests:
      cpu: 200m
      memory: 256Mi
    web: true
    objectStore:
    - ingress-uploads-perma
    kafkaTopics:
    - replicas: 5
      partitions: 5
      topicName: platform.upload.advisor

parameters:
- name: INGRESS_STAGEBUCKET
  value: insights-dev-upload-perm
- name: INGRESS_REJECTBUCKET
  value: insights-dev-upload-rejected
- name: INGRESS_VALIDTOPICS
  value: advisor,advisor-pup,compliance,hccm,qpc,rhv,testareno,tower,leapp-reporting,topological-inventory,buckit,xavier,mkt
- name: INGRESS_INVENTORYURL
  value: http://insights-inventory:8080/api/inventory/v1/hosts
- name: INGRESS_MAXSIZE
  value: '104857600'
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- name: REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/insights-ingress
- description: ClowdEnv Name
  name: ENV_NAME
  requred: true

